import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "/styles/globals.scss";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/global/navigation/Navbar";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/global/footer/Footer";
import { Spinner } from "@/components/ui/spinner";

const fontStyle = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Stacked Insights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${fontStyle.className} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ClerkLoading>
              <div className="flex min-h-screen items-center justify-center">
                <div className="flex items-center gap-3">
                  <Spinner className="flex">
                    Verifying identity. This may take a moment...
                  </Spinner>
                </div>
              </div>
            </ClerkLoading>
            <Navbar />
            <ClerkLoaded>{children}</ClerkLoaded>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
